Repository puj-course/FIS_2530_G2, pull requests merged in 2025-08, with the labels that each got.

#38 Develop
  .gitkeep
Labels: AYUDA

#42 Features taller2 jm
  SIS/docs/architecture/idea1.txt
  SIS/docs/project_records/poker-scrum-2meet.md
Labels: despliegue y documentación, prioridad: baja

#49 Complete Information about Sprint Planning Iteration 2
  docs/project_records/poker-scrum-2meet.md
  docs/project_records/sprintplanningIT2.md
Labels: despliegue y documentación
