Repository puj-course/FIS_2530_G2, pull requests merged in 2025-09, with the labels that each got.

#55 Minimun Requirements
  docs/investigation/minimun_req.md
Labels: despliegue y documentación

#62 docs: diagrama ebc realizado closes #57
  docs/architecture/ebc_diagram.jpg
Labels: despliegue y documentación, diseño

#61 Diagrama de Componentes
  docs/architecture/Diagrama Componentes.jpeg
Labels: despliegue y documentación

#63 NF: Diagrama de componentes
  docs/architecture/DiagramaClases.pdf
Labels: diseño

#65 Add files via upload
  docs/architecture/TUML.pdf
Labels: despliegue y documentación
